### ISSUE TITLE
Etiquetas en Fotos

### ISSUE THREAD

**Issue by RodrigoEspinosa** [TuMovida/TuMovida#1]
Agregar la posibilidad de **ver y añadir etiquetas** en las fotos del **photoDisplay**
Los archivos son: `ajax/photoDisplay.php` y `js/photoDisplay.js`.

Hay que encontrar una librería para jQuery que haga esto. Yo vi algunas que están buenas. Puede alguien probarlas para ir viendo cuales son sus beneficios y complicaciones en cada una? 

La mejor la modificamos y agregamos al sitio.

**Comment by dimartiro** [comment]
etiquetas en el sentido de etiquetar personas? o etiquetas tipo tags para busqueda?

**Comment by RodrigoEspinosa** [comment]
Etiquetar personas en las fotos. Se puede usar alguno de estos plug-ins: http://www.designdim.com/2011/11/top-4-jquery-photo-tagging-plugins/

**Comment by dimartiro** [comment]
impecable voy a ver si le meto a eso.. esta es una buena zona para poner lista de tareas... igual opino que no vendria mal tener algun manual que explique como funciona y esta hecha la web, para los nuevos que recien entramos

**Comment by RodrigoEspinosa** [comment]
Dale, arranco a escribir algo para eso. ¿Cómo te parece que se organizaría mejor todo?

**Comment by dimartiro** [comment]
estaria bueno hacer una especie de "diagrama" que muestre como estan conectadas las cosas.. y mas que nada pensar en tener todo organizado en carpetas tipo modulos, donde cualquier programador se puede poner a crear nuevos modulos, sin necesidad de saber como esta hecho el resto de la web, asi a medida que agreguemos gente al proyecto, el trabajo se hace mas rapido y simple, porque no tienen que entender como esta hecho y conectado todo, sino que se meten a programar sus "modulos" de una

**Comment by RodrigoEspinosa** [comment]
**Buena propuesta**, voy a ver que puedo hacer.

_Cualquier consulta me tenes en Skype._

**Comment by dimartiro** [comment]
dale impecable :D voy a leer un poco la web para entenderla mejor, pero eso de los modulos esta bueno para agilitar el trabajo
