### ISSUE TITLE
Slider de nuevas opciones en la página

### ISSUE THREAD

**Issue by RodrigoEspinosa** [TuMovida/TuMovida#10]
Agregar un slider para mostrar las nuevas opciones en la página.

**Comment by martinalvarez1992** [comment]
no entiendo como nuevas opciones?

**Comment by RodrigoEspinosa** [comment]
Lo que ya hiciste, nada más por hacer. Las _nuevas opciones_ son Registra tu evento, ¿Queres ser RRPP?, etc.
