### ISSUE TITLE
error al entrar a "Mis Compras"

### ISSUE THREAD

**Issue by dimartiro** [TuMovida/TuMovida#13]
Al entrar a Mis Compras sin tener ninguna compra hecha la pantalla se torna grisasea con un "popup" que dice "Mis Compras" pero nada dentro....
se podría agregar un "no hiciste compras todavia" o algo :)

**Comment by RodrigoEspinosa** [comment]
Solucionado. Agregado "**No hiciste compras todavía**" en caso de nulidad.
