### ISSUE TITLE
Contador de comentarios

### ISSUE THREAD

**Issue by RodrigoEspinosa** [TuMovida/TuMovida#3]
Contador de comentarios en Fotos.

**Comment by RodrigoEspinosa** [comment]
Agregado. La diferencia se encuentra en `ajax/album.php`

```
$comentarios = $conn->query("SELECT * FROM comentarios WHERE id_pagina LIKE 'f_".$id."-%'");
$nroComments = mysql_num_rows($comentarios);
```

Tan simple como eso, y para mostrar el número es imprimir la variable `nroComments`.
Lo único que falta es agregarlo a cada una de las imagenes con un icono lindo.

**Comment by EmmanuelHV** [comment]
bien de bien

**Comment by RodrigoEspinosa** [comment]
@martinalvarez1992 cuando ponga hoy un icono para los comments miralo y decime que te parece.
