### ISSUE TITLE
Fecha comentarios

### ISSUE THREAD

**Issue by RodrigoEspinosa** [TuMovida/TuMovida#5]
En los comentarios de los usuarios dentro sus perfiles aparece "Hace XX <horas/minutos/días/etc> en <lugar del evento>". Esto esta fallando bastante. A veces se come meses y cosas así. Hay que revisar ese código y crear una clase que se llame `Util` para conversiones de tiempos y fechas.

**Comment by dimartiro** [comment]
php no tiene funciones para manejar fechas ya?

**Comment by RodrigoEspinosa** [comment]
Si pero la idea es que devuelva un formato lindo, como tiene facebook. Ejemplo: "_Hace 4 minutos_". 
Esto es lo que hay hecho: 

```
    $fecha =  time() - strtotime($fechaCorrect);
    if ($fecha > 60){
            $fecha = round($fecha / 60);
            if ($fecha > 60){
                $fecha = round($fecha / 60);
                if ($fecha > 24){
                    $fecha = round($fecha /24);
                    ($fecha > 1) ? $fecha = $fecha." días" : $fecha = $fecha." día";
                }else{
                    $fecha = $fecha." minutos"; 
                }
            }else{
                $fecha = $fecha. " segundos";
            }
```

**Comment by dimartiro** [comment]
ahh ahi va
