### ISSUE TITLE
Bajas en Fotos

### ISSUE THREAD

**Issue by RodrigoEspinosa** [TuMovida/TuMovida#7]
Darle al usuario la posibilidad de realizar una petición para dar de baja una foto. Hay que ver qué sería lo mejor acá. 

Probablemente lo mejor sea que cuando un usuario haga click en el anchor que diga "_Petición de baja para esta Foto_" o similar, se tomen todos sus datos automáticamente y se envíen a info@tumovida.com.uy para ser removidos manualmente.

**Comment by dimartiro** [comment]
que tal si se acumulan y si hay mas de 10 la foto se elimina automaticamente, si no dar la posibilidad de escribir la razon para borrarla, y que se envie un mail con eso, y si la razon es buena.. en ese caso se borraria manualmente

**Comment by RodrigoEspinosa** [comment]
Las dos son buenas ideas. Habría que poner ambas. 
El motivo acá es que las fotos son subidas por el equipo de TM entonces pasa re seguido de gente que dice que salió horrible y la quiere sacar. Cosas así.

**Comment by dimartiro** [comment]
claro claro, por eso mismo, tambien puede tener que ver con las personas etiquetadas, si mas de la mitad de esas personas la "denuncia" se eliminaria automaticameante

**Comment by RodrigoEspinosa** [comment]
Interesante. Entonces 1° Paso sería sacar los tags.
