### ISSUE TITLE
Comprimir la lista de JavaScripts

### ISSUE THREAD

**Issue by RodrigoEspinosa** [TuMovida/TuMovida#8]
Crear una aplicación en Python para auto-compilar todos los archivos de _JS \* organizados en una lista en un solo archivo. *Minificarlo_ en compile.min.js

**Comment by RodrigoEspinosa** [comment]
@diego2737 vos te podes encargar de esto?

**Comment by dimartiro** [comment]
osea... un script que te junte todos los js en uno solo?

**Comment by dimartiro** [comment]
no seria poco optimo? osea... no es mas practico cargar 20 archivos de 100kb en vez de uno de 2mb ? porque en ese caso no se ejecutaria ningun script js hasta que este cargado el archivo completo.. y va a tardar un poco mas que antes en cargar

**Comment by RodrigoEspinosa** [comment]
Al contrario, siempre es más rápido cargar 1 archivo que 20 que pesen igual. De cualquier forma, la idea es a su vez minificarlos. 
Lo que quiero hacer es un MinMyMerge para JS.

**Comment by dimartiro** [comment]
ok, no estoy de acuerdo, pero lo programo... igual me parece mas util cargar un archivo de 100kb que se ejecute a esperar que se cargue uno de 2mb para que se ejecute el script que estaba en esos 100kb... 
igual me pongo a hacer el script hoy :)

**Comment by RodrigoEspinosa** [comment]
No, si no estas de acuerdo no lo hagas. Yo sugiero cosas para que se metan en el código pero mi idea es que ustedes hagan cosas que les inspire hacer. 

@martinalvarez1992 , después te voy a preguntar un par de cosas sobre tu carrera. Les dejo para todos un articulo copado https://developers.google.com/speed/

**Comment by dimartiro** [comment]
naaa lo voy a hacer para meterle a la web!! asi depaso hago algo pero igual me parece mas practico cargar un script liviano a esperar que se cargue uno mas pesado solo para ejecutar una linea de codigo

**Comment by RodrigoEspinosa** [comment]
Es comprimir también, ver todo lo que carga cuando el documento esta pronto y dejarlos en el mismo lugar. 
Hay muchos archivos que tienen 

```
$(document).on("ready", function(){
    ...
});
```

**Comment by dimartiro** [comment]
que se podria simplificar a 

```
$(document).ready(function(){
    ...
});
```

**Comment by RodrigoEspinosa** [comment]
La forma correcta de hacerlo en la última versión de jQuery es la que puse yo, a lo que me refería es a compaginar todos los eventos "on ready" en uno solo, dentro de un solo archivo.

**Comment by dimartiro** [comment]
uyy va a estar lindo :D

**Comment by RodrigoEspinosa** [comment]
jajaja, mismo. Hoy te conocemos por G+ entonces?

**Comment by dimartiro** [comment]
sii :D a que hora? me entere de casualidad por Adrian que justo me dijo

**Comment by RodrigoEspinosa** [comment]
22:30 =)

**Comment by dimartiro** [comment]
dale ahi estoy pasame tu plus

**Comment by RodrigoEspinosa** [comment]
Creo que ya te agregue pero es https://plus.google.com/112445322683959020265
